### ISSUE TITLE
SAMSUNG Galaxy S20+Login Google Error

### ISSUE THREAD

**Issue by wjwang0914** [Web3Auth/web3auth-android-sdk#28]
SAMSUNG Galaxy S20+ login google success after error,Error is as follows:
"Could not get result from torus nodes Unable to resolve enough promises”

**Comment by shahbaz17** [comment]
Hey @wjwang0914 

Sorry for the late reply. Could you try again with the latest SDK? And let us know if you can reproduce the same or not.

**Comment by grvgoel81** [comment]
Please try with the latest release. It is resolved.
