### ISSUE TITLE
How to connect with an existing wallet?

### ISSUE THREAD

**Issue by amilcar-andrade** [Web3Auth/web3auth-android-sdk#31]
In the documentation, it seems that the web3auth product can also allow you to connect with an existing wallet. How is that possible using this SDK?

**Comment by Alydero19** [comment]
Nice

**Comment by shahbaz17** [comment]
Hey @amilcar-andrade @Alydero19 

I'm sorry for not getting back to you sooner. 

Our Mobile SDK doesn't have the feature to allow login with the existing wallet. It's only supported on Web SDK. We'll keep you posted if it comes in the future release.
