### ISSUE TITLE
The user agent does not support public key credentials.

### ISSUE THREAD

**Issue by yuejunfei** [Web3Auth/web3auth-android-sdk#38]
Hello, I use Web3Auth to access the Android example, and open https://sdk.openlogin.com/login# with the browser of the Android system. It prompts me that The user agent does not support public key credentials. How can I solve this error?

**Comment by shahbaz17** [comment]
Hey @yuejunfei 

Sorry for the late reply. Could you try again with the latest SDK? And let us know if you can reproduce the same or not.
