### ISSUE TITLE
Compilation error if my app has its own Application class in manifest

### ISSUE THREAD

**Issue by StudentNSK** [Web3Auth/web3auth-android-sdk#39]
Hey, my android app has Application class and I can't use 3.0.0 SDK because it has Application class too.

Heres the compilation error:
```
Error:
	Attribute application@name value=(com.xxx.xxx.xxx) from AndroidManifest.xml:13:9-47
	is also present at [org.torusresearch:web3auth-android-sdk:3.0.0] AndroidManifest.xml:17:18-62 value=(com.web3auth.core.Web3AuthApp).
	Suggestion: add 'tools:replace="android:name"' to <application> element at AndroidManifest.xml:9:5-105:19 to override.
```

**Comment by shahbaz17** [comment]
Hey @StudentNSK 

I'm sorry for not getting back to you sooner. 

Could you try again with the latest SDK? And let us know if you can reproduce the same or not.

**Comment by grvgoel81** [comment]
Hey @StudentNSK 

Beefore android version 3.0.0 we are using activity context in SDK. But from 3.0.0 we are using application context in SDK for some usecase. You can just use 'tools:replace="android:name' inside application tag in manigest.xml.
