### ISSUE TITLE
please upgrade security-crypto to "1.1.0-alpha04"

### ISSUE THREAD

**Issue by cooaer** [Web3Auth/web3auth-android-sdk#42]
web3auto-android-sdk:3.2.0 depends on protobuf-lite:3.0.1 that last updated at Jul 28, 2016。
<img width="542" alt="image" src="https://user-images.githubusercontent.com/4060489/218956542-aca11bed-6a7e-4cf2-9046-5e04ab99cf04.png">
[Google : Use Java Protocol Buffers on Android](https://github.com/protocolbuffers/protobuf/tree/main/java#use-java-protocol-buffers-on-android)
For Android users, it's recommended to use protobuf Java Lite runtime because of its smaller code size. Java Lite runtime also works better with Proguard because it doesn't rely on Java reflection and is optimized to allow as much code stripping as possible. You can following these [instructions to use Java Lite runtime](https://github.com/protocolbuffers/protobuf/blob/main/java/lite.md).

The latest version of security-crypto:1.1.0-alpha04 depens on the latest version of think-android:1.7.0 that remove protobuf-lite。

so, please upgrade security-crypto to "1.1.0-alpha04"。

**Comment by cooaer** [comment]
My project depends on protobuf-java-lite which is in conflict with protobuf-lite.

**Comment by grvgoel81** [comment]
PR is out for it. https://github.com/Web3Auth/web3auth-android-sdk/pull/43
