### ISSUE TITLE
LogOut never seems to actually complete

### ISSUE THREAD

**Issue by MattRobertson-AND** [Web3Auth/web3auth-android-sdk#45]
Coming over from the using the Flutter SDK - 
We seem to be seeing some odd behaviour with the logout on a project

It seems that the logout completable future will never actually complete, meaning that if we're awaiting it over on the flutter side, it'll never actually return.
The problem seems to be here

https://github.com/Web3Auth/web3auth-android-sdk/blob/71969f686c404777072e36295354134d43528246/core/src/main/java/com/web3auth/core/Web3Auth.kt#L146

If I understand the code correctly, the setResultUrl, is supposed to check if the private key is `null` or blank (ie ` ` or ``)

However, the response I seem to be getting from the logout function is with an auth which when decoded gives me
```
{"privKey":"0000000000000000000000000000000000000000000000000000000000000000","sessionId":"","ed25519PrivKey":"0000000000000000000000000000000000000000000000000000000000000000[load of chars which are not 0s removed just in case]","userInfo":{}}
```

thus not being blank or null, and thus causing the setResultUrl for the logout completable future to be skipped.

**Comment by javichaques** [comment]
Hi, we have the same problem

**Comment by grvgoel81** [comment]
Its resolved with PR : https://github.com/Web3Auth/web3auth-android-sdk/pull/53
