### ISSUE TITLE
self-hosted tKey integration

### ISSUE THREAD

**Issue by krisgrm** [Web3Auth/web3auth-android-sdk#49]
Hello, I'd like to use this library along with self-hosting the tkey component https://web3auth.io/docs/sdk/tkey/

can i integrate this somehow directly with android sdk ?

**Comment by grvgoel81** [comment]
Hi,

Our standard support has moved to the Web3Auth Community Portal(http://community.web3auth.io). Please search and/or create a topic there for us to help you in the best way possible. Feel free to subscribe to the enterprise plan for a dedicated support channel.
