### ISSUE TITLE
After logging out and logging in with the same login provider credentials, wallet credentials changes

### ISSUE THREAD

**Issue by Tekrajs** [Web3Auth/web3auth-android-sdk#51]
Hi,

I adopted the documentation and ran the application. I can login using Google and the address is successfully returned when calling the `getAddress` method. But after I logs out and login with the same gmail then the address is changed. Is it the expected behaviour?

If so how can I keep the same address for same gmail login?

Thanks

**Comment by grvgoel81** [comment]
Pls try with latest sdk version.
