### ISSUE TITLE
getting weird error in building

### ISSUE THREAD

**Issue by razaghimahdi** [Web3Auth/web3auth-android-sdk#63]
so after migrating to 4.0.8, while building I get this :
Can't determine type for tag '<macro name="m3_comp_assist_chip_container_shape">?attr/shapeAppearanceCornerSmall</macro>'

why is that? how to handle that? i tried to change  some important libraries but it didn't change anything, so what is going on?

**Comment by grvgoel81** [comment]
Released new version of android-sdk. It should be resolved now.
